import { Asana } from "./AsanaDefinitions";

export const ASANA_DB: Asana[] = [
  // --- BEGINNER (초급) ---
  { id: "1", english: "Mountain Pose", sanskrit: "Tadasana", level: "Beginner", type: "Standing" },
  { id: "2", english: "Child's Pose", sanskrit: "Balasana", level: "Beginner", type: "Restorative" },
  { id: "3", english: "Downward-Facing Dog", sanskrit: "Adho Mukha Svanasana", level: "Beginner", type: "Inversion" },
  { id: "4", english: "Warrior I", sanskrit: "Virabhadrasana I", level: "Beginner", type: "Standing" },
  { id: "5", english: "Warrior II", sanskrit: "Virabhadrasana II", level: "Beginner", type: "Standing" },
  { id: "6", english: "Tree Pose", sanskrit: "Vrikshasana", level: "Beginner", type: "Standing" },
  { id: "7", english: "Cat Pose", sanskrit: "Marjaryasana", level: "Beginner", type: "Sitting" },
  { id: "8", english: "Cow Pose", sanskrit: "Bitilasana", level: "Beginner", type: "Sitting" },
  { id: "9", english: "Cobra Pose", sanskrit: "Bhujangasana", level: "Beginner", type: "Backbend" },
  { id: "10", english: "Bridge Pose", sanskrit: "Setu Bandhasana", level: "Beginner", type: "Backbend" },
  { id: "11", english: "Easy Pose", sanskrit: "Sukhasana", level: "Beginner", type: "Sitting" },
  { id: "12", english: "Corpse Pose", sanskrit: "Shavasana", level: "Beginner", type: "Restorative" },
  { id: "13", english: "Plank Pose", sanskrit: "Phalakasana", level: "Beginner", type: "Arm Balance" },
  { id: "14", english: "Happy Baby Pose", sanskrit: "Ananda Balasana", level: "Beginner", type: "Restorative" },
  { id: "15", english: "Butterfly Pose", sanskrit: "Baddha Konasana", level: "Beginner", type: "Sitting" },

  // --- INTERMEDIATE (중급) ---
  { id: "16", english: "Warrior III", sanskrit: "Virabhadrasana III", level: "Intermediate", type: "Standing" },
  { id: "17", english: "Triangle Pose", sanskrit: "Trikonasana", level: "Intermediate", type: "Standing" },
  { id: "18", english: "Half Moon Pose", sanskrit: "Ardha Chandrasana", level: "Intermediate", type: "Standing" },
  { id: "19", english: "Crow Pose", sanskrit: "Bakasana", level: "Intermediate", type: "Arm Balance" },
  { id: "20", english: "Pigeon Pose", sanskrit: "Eka Pada Rajakapotasana", level: "Intermediate", type: "Sitting" },
  { id: "21", english: "Boat Pose", sanskrit: "Navasana", level: "Intermediate", type: "Sitting" },
  { id: "22", english: "Camel Pose", sanskrit: "Ustrasana", level: "Intermediate", type: "Backbend" },
  { id: "23", english: "Eagle Pose", sanskrit: "Garudasana", level: "Intermediate", type: "Standing" },
  { id: "24", english: "Chair Pose", sanskrit: "Utkatasana", level: "Intermediate", type: "Standing" },
  { id: "25", english: "Extended Side Angle", sanskrit: "Utthita Parsvakonasana", level: "Intermediate", type: "Standing" },
  { id: "26", english: "Shoulder Stand", sanskrit: "Salamba Sarvangasana", level: "Intermediate", type: "Inversion" },
  { id: "27", english: "Plow Pose", sanskrit: "Halasana", level: "Intermediate", type: "Inversion" },
  { id: "28", english: "Wild Thing", sanskrit: "Camatkarasana", level: "Intermediate", type: "Backbend" },
  { id: "29", english: "Lord of the Dance", sanskrit: "Natarajasana", level: "Intermediate", type: "Standing" },
  { id: "30", english: "Four-Limbed Staff", sanskrit: "Chaturanga Dandasana", level: "Intermediate", type: "Arm Balance" },
  { id: "31", english: "Garland Pose", sanskrit: "Malasana", level: "Intermediate", type: "Standing" },
  { id: "32", english: "Revolved Triangle", sanskrit: "Parivrtta Trikonasana", level: "Intermediate", type: "Twist" },
  { id: "33", english: "Cow Face Pose", sanskrit: "Gomukhasana", level: "Intermediate", type: "Sitting" },
  { id: "34", english: "Hero Pose", sanskrit: "Virasana", level: "Intermediate", type: "Sitting" },
  { id: "35", english: "Bow Pose", sanskrit: "Dhanurasana", level: "Intermediate", type: "Backbend" },

  // --- ADVANCED (고급) ---
  { id: "36", english: "Headstand", sanskrit: "Salamba Sirsasana", level: "Advanced", type: "Inversion" },
  { id: "37", english: "Wheel Pose", sanskrit: "Urdhva Dhanurasana", level: "Advanced", type: "Backbend" },
  { id: "38", english: "Forearm Stand", sanskrit: "Pincha Mayurasana", level: "Advanced", type: "Inversion" },
  { id: "39", english: "Handstand", sanskrit: "Adho Mukha Vrksasana", level: "Advanced", type: "Inversion" },
  { id: "40", english: "Eight-Angle Pose", sanskrit: "Astavakrasana", level: "Advanced", type: "Arm Balance" },
  { id: "41", english: "King Pigeon Pose", sanskrit: "Rajakapotasana", level: "Advanced", type: "Backbend" },
  { id: "42", english: "Firefly Pose", sanskrit: "Tittibhasana", level: "Advanced", type: "Arm Balance" },
  { id: "43", english: "Scorpion Pose", sanskrit: "Vrischikasana", level: "Advanced", type: "Inversion" },
  { id: "44", english: "Side Crow Pose", sanskrit: "Parsva Bakasana", level: "Advanced", type: "Arm Balance" },
  { id: "45", english: "Monkey Pose", sanskrit: "Hanumanasana", level: "Advanced", type: "Sitting" },
  { id: "46", english: "Peacock Pose", sanskrit: "Mayurasana", level: "Advanced", type: "Arm Balance" },
  { id: "47", english: "Compass Pose", sanskrit: "Parivrtta Surya Yantrasana", level: "Advanced", type: "Sitting" },
  { id: "48", english: "Scale Pose", sanskrit: "Tolasana", level: "Advanced", type: "Arm Balance" },
  { id: "49", english: "Flying Pigeon", sanskrit: "Eka Pada Galavasana", level: "Advanced", type: "Arm Balance" },
  { id: "50", english: "Upward Bow", sanskrit: "Urdhva Dhanurasana", level: "Advanced", type: "Backbend" },
];